import { HttpClient } from '@angular/common/http';
import { EventEmitter, Injectable, Output } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { BehaviorSubject, map, Observable } from 'rxjs';
import { IProducts } from '../products';
import { Filter } from '../filter';
@Injectable({
  providedIn: 'root'
})
export class ProductsService {
  form =  FormGroup;
  // filter: import("/home/neelesh/Desktop/Project-3/myShop/src/app/filter").Filter;
  constructor(private http:HttpClient) { }
  products: IProducts[] = [];
  filteredProducts: IProducts[] = [];
  @Output() event = new EventEmitter();
  private baseUrl = 'https://localhost:4200/products';

  searchProducts(thekeyword:string): Observable<IProducts[] | undefined>
 {
  // Need to build URL based on the Keyword
  const searchUrl=`${this.baseUrl}/search/findbyNameContaining?name=${thekeyword}`;
  return this.http.get<IProducts[]>(searchUrl).pipe(map((res:any)=>res.embedded.products));
 }

  private readonly _filter = new BehaviorSubject<Filter>({name: "", categories:[]});
  readonly filter$ = this._filter.asObservable();

  get filter(): Filter {
    return this._filter.getValue();
  }

  set filter(val: Filter) {
    this._filter.next(val);
  }

  getProduct(id: number): Observable<IProducts | undefined> {
    const product_id = this.products.find(product => product_id === product_id);
    return product_id;
 }



  // Mene yahan pe WO fake API Store se bahut sare product ka data get krke ek response res mai daal diya jo ki getProducts() se call hoga
  getProducts() {
    return [
      {
        product_id: 1,
        product_name: "Here&Now ",
        product_price: 699,
        product_description: "Solid Round Neck T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "1.1.jpg",
        product_img2: "1.2.jpg",
        product_rating:4,
        product_quanity: 1,

      },
      {
        product_id: 2,
        product_name: "HIGHLANDER",
        product_price: 1199,
        product_description: "Cotton Pure T-Shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "2.2.jpg",
        product_img2: "2.1.jpg",
        product_rating:3.5,
        product_quanity: 1,
      },
      {
        product_id: 3,
        product_name: "ROADSTER",
        product_price: 899,
        product_description: "Solid round neck T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "3.1.jpg",
        product_img2: "3.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id: 4,
        product_name: "Here&Now",
        product_price: 399,
        product_description: "Printed T-shirt long sleeves",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "4.1.jpg",
        product_img2: "4.2.jpg",
        product_rating:3,
        product_quanity: 1,
      },
      {
        product_id: 5,
        product_name: "HIGHLANDER",
        product_price: 1599,
        product_description: "Solid Round Neck T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "5.1.jpg",
        product_img2: "5.2.jpg",
        product_rating:2.6,
        product_quanity: 1,
      },
      {
        product_id: 6,
        product_name: "Here&Now",
        product_price: 799,
        product_description: "Graphic Cottono T-Shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "6.1.jpg",
        product_img2: "6.2.jpg",
        product_rating:4.1,
        product_quanity: 1,
      },
      {
        product_id: 7,
        product_name: "HRX",
        product_price: 1899,
        product_description: "Slim Tropical Printed Cotton",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "7.1.jpg",
        product_img2: "7.2.jpg",
        product_rating:4.9,

        product_quanity: 1,
      },
      {
        product_id: 8,
        product_name: "Cantabil",
        product_price: 1799,
        product_description: "Ultralyte Men Running T-Shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "8.1.jpg",
        product_img2: "8.2.jpg",
        product_rating:3.8,

        product_quanity: 1,
      },
      {
        product_id: 9,
        product_name: "Levis",
        product_price: 1999,
        product_description: "Printed Cotton Pure Cotton T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "9.1.jpg",
        product_img2: "9.2.jpg",
        product_rating:3.6,

        product_quanity: 1,
      },
      {
        product_id: 10,
        product_name: "HIGHLANDER",
        product_price: 899,
        product_description: "Printed Atleisure Cotton Pure",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "10.1.jpg",
        product_img2: "10.2.jpg",
        product_rating:3,

        product_quanity: 1,
      },
      {
        product_id: 11,
        product_name: "ROADSTER",
        product_price: 999,
        product_description: "Men Solid Fitted Cotton",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "11.1.jpg",
        product_img2: "11.2.jpg",
        product_rating:4.5,

        product_quanity: 1
      },
      {
        product_id: 12,
        product_name: "HRX",
        product_price: 1599,
        product_description: "Pure Cotton T-shirt Logo",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "12.1.jpg",
        product_img2: "12.2.jpg",
        product_rating:3.9,
        product_quanity: 1
      },
      {
        product_id: 13,
        product_name: "Here&Now",
        product_price: 599,
        product_description: "Typography Print T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "13.1.jpg",
        product_img2: "13.2.jpg",
        product_rating:4.8,
        product_quanity: 1
      },
      {
        product_id: 14,
        product_name: "Mufti",
        product_price: 899,
        product_description: "Rapid Dry T-Shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "14.1.jpg",
        product_img2: "14.2.jpg",
        product_rating:4.1,
        product_quanity: 1
      },
      {
        product_id: 15,
        product_name: "Cantabil",
        product_price: 1299,
        product_description: "Cotton Printed Graphic T-Shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "15.1.jpg",
        product_img2: "15.2.jpg",
        product_rating:4.3,
        product_quanity: 1
      },
      {
        product_id: 16,
        product_name: "ROADSTER",
        product_price: 699,
        product_description: "Raglan Sleeved T-Shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "16.1.jpg",
        product_img2: "16.2.jpg",
        product_rating:3.9,
        product_quanity: 1
      },
      {
        product_id: 17,
        product_name: "HRX",
        product_price: 1299,
        product_description: "Men Printed Loose T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "17.1.jpg",
        product_img2: "17.2.jpg",
        product_rating:3.8,
        product_quanity: 1
      },
      {
        product_id: 18,
        product_name: "Cantabil",
        product_price: 1599,
        product_description: "Curl Edge Cotton T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "18.1.jpg",
        product_img2: "18.2.jpg",
        product_rating:4.4,
        product_quanity: 1
      },
      {
        product_id: 19,
        product_name: "Here&Now",
        product_price: 499,
        product_description: "Rapid Dry Training T-Shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "19.1.jpg",
        product_img2: "19.2.jpg",
        product_rating:2.9,
        product_quanity: 1
      },
      {
        product_id: 20,
        product_name: "Mufti",
        product_price: 999,
        product_description: "Solid Nech Pure Cotton",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "20.1.jpg",
        product_img2: "20.2.jpg",
        product_rating:3.9,
        product_quanity: 1
      },
      {
        product_id: 21,
        product_name: "Levis",
        product_price: 1299,
        product_description: "Printed Cotton Pure Cotton T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "21.1.jpg",
        product_img2: "21.2.jpg",
        product_rating:4.4,
        product_quanity: 1
      },
      {
        product_id: 22,
        product_name: "ROADSTER",
        product_price: 599,
        product_description: "Rapid Dry Raglan Polo T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "22.1.jpg",
        product_img2: "22.2.jpg",
        product_rating:4.3,
        product_quanity: 1
      },
      {
        product_id: 23,
        product_name: "HIGHLANDER",
        product_price: 499,
        product_description: "Stripped Cotton T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "23.1.jpg",
        product_img2: "23.2.jpg",
        product_rating:4.3,
        product_quanity: 1
      },
      {
        product_id: 24,
        product_name: "Here&Now",
        product_price: 399,
        product_description: "Longlone T-shirt with Raw Edge",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "24.1.jpg",
        product_img2: "24.2.jpg",
        product_rating:4.1,
        product_quanity: 1
      },
      {
        product_id: 25,
        product_name: "Mufti",
        product_price: 1499,
        product_description: "Solid Polo T-shirt",
        product_category: "Men",
        product_category_type: "TShirts",
        product_img: "25.1.jpg",
        product_img2: "25.2.jpg",
        product_rating:3.9,
        product_quanity: 1
      },

      ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
      ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
      ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

      {
        product_id: 26,
        product_name: "Roadster",
        product_price: 999,
        product_description: "Fit cotton polo shirt",
        product_category: "Men",
        product_category_type: "Shirt",
        product_img: "26.1.jpg",
        product_img2: "26.2.jpg",
        product_rating:3.9,
        product_quanity: 1
      },
      {
        product_id: 27,
        product_name: "Dennis Lingo",
        product_price: 1899,
        product_description: "Solid polo shirt",
        product_category: "Men",
        product_category_type: "Shirt",
        product_img: "27.1.jpg",
        product_img2: "27.2.jpg",
        product_rating:3.9,
        product_quanity: 1
      },
      {
        product_id: 28,
        product_name: "WROGN",
        product_price: 899,
        product_description: "Slim fit casual shirt",
        product_category: "Men",
        product_category_type: "Shirt",
        product_img: "28.1.jpg",
        product_img2: "28.2.jpg",
        product_rating:3.9,
        product_quanity: 1
      },
      {
        product_id:29,
        product_name:"Roadster",
        product_price:799,
        product_description:"Printed casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "29.1.jpg",
        product_img2: "29.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:30,
        product_name:"Dennis Lingo",
        product_price:2599,
        product_description:"full slim fit cotton shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "30.1.jpg",
        product_img2: "30.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:31,
        product_name:"WROGN",
        product_price:1199,
        product_description:"Men slim fit casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "31.1.jpg",
        product_img2: "31.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:32,
        product_name:"Roadster",
        product_price:899,
        product_description:"Men full cotton shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "32.1.jpg",
        product_img2: "32.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:33,
        product_name:"Here&Now",
        product_price:799,
        product_description:"Men cotton casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "33.1.jpg",
        product_img2: "33.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:34,
        product_name:"WROGN",
        product_price:1199,
        product_description:"Slim fit casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "34.1.jpg",
        product_img2: "34.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:35,
        product_name:"HIGHLANDER",
        product_price:1299,
        product_description:"Men slim fit casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "35.1.jpg",
        product_img2: "35.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:36,
        product_name:"Roadster",
        product_price:1399,
        product_description:"Washed casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "36.1.jpg",
        product_img2: "36.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:37,
        product_name:"WROGN",
        product_price:1899,
        product_description:"Men slim fit casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "37.1.jpg",
        product_img2: "37.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:38,
        product_name:"Here&Now",
        product_price:999,
        product_description:"Slim fit striped casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "38.1.jpg",
        product_img2: "38.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:39,
        product_name:"Levis",
        product_price:2199,
        product_description:"Regular fit casual shirt Levi's",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "39.1.jpg",
        product_img2: "39.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:40,
        product_name:"Roadster",
        product_price:1699,
        product_description:"Men pure cotton shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "40.1.jpg",
        product_img2: "40.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:41,
        product_name:"HIGHLANDER",
        product_price:1299,
        product_description:"Slim fit casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "41.1.jpg",
        product_img2: "41.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:42,
        product_name:"WROGN",
        product_price:1199,
        product_description:"Men slim casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "42.1.jpg",
        product_img2: "42.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:43,
        product_name:"HIGHLANDER",
        product_price:1599,
        product_description:"Long sleeves cotton shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "43.1.jpg",
        product_img2: "43.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:44,
        product_name:"Here&Now",
        product_price:699,
        product_description:"Slim fit checked casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "44.1.jpg",
        product_img2: "44.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:45,
        product_name:"Mast & Harbour",
        product_price:499,
        product_description:"Men slim fit casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "45.1.jpg",
        product_img2: "45.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:46,
        product_name:"Mast & Harbour",
        product_price:1299,
        product_description:"Slim casual shirt cotton",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "46.1.jpg",
        product_img2: "46.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:47,
        product_name:"Mast & Harbour",
        product_price:799,
        product_description:"Regular fit shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "47.1.jpg",
        product_img2: "47.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:48,
        product_name:"Mast & Harbour",
        product_price:399,
        product_description:"Cotton casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "48.1.jpg",
        product_img2: "48.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:49,
        product_name:"Levis",
        product_price:2199,
        product_description:"100% cotton casual shirt",
        product_category:"Men",
        product_category_type: "Shirt",
        product_img: "49.1.jpg",
        product_img2: "49.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      // {
      //   product_id:50,
      //   product_name:"WROGN",
      //   product_price:1299,
      //   product_description:"Men Slim Fit Casual Shirt",
      //   product_category:"",
      //   product_category_type: "Shirt",
      //   product_img: "",
      //   product_img2: "",
      //   product_rating:3.9,
      //   product_quanity: 1,
      // },


///                   Ladies's JACKET

      {
        product_id:51,
        product_name:"ZARA",
        product_price:2199,
        product_description:"Oversized bomber blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "51.1.jpg",
        product_img2: "51.2.jpg",
        product_rating:4.9,
        product_quanity: 1,
      },
      {
        product_id:52,
        product_name:"ZARA",
        product_price:1899,
        product_description:"Fauk woolen oversized blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "52.1.jpg",
        product_img2: "52.2.jpg",
        product_rating:4.1,
        product_quanity: 1,
      },
      {
        product_id:53,
        product_name:"Denim",
        product_price:3500,
        product_description:"Cropped cotton blazer slim fit",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "53.1.jpg",
        product_img2: "53.2.jpg",
        product_rating:3.0,
        product_quanity: 1,
      },
      {
        product_id:54,
        product_name:"ZARA",
        product_price:2899,
        product_description:"Satine black fitted blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "54.1.jpg",
        product_img2: "54.2.jpg",
        product_rating:4.1,
        product_quanity: 1,
      },
      {
        product_id:55,
        product_name:"Denim",
        product_price:1499,
        product_description:"Taylor fox fitted long blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "55.1.jpg",
        product_img2: "55.2.jpg",
        product_rating:4.0,
        product_quanity: 1,
      },
      {
        product_id:56,
        product_name:"ZARA",
        product_price:1999,
        product_description:"Overshirt with contrast embroidery",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "56.1.jpg",
        product_img2: "56.2.jpg",
        product_rating:4.2,
        product_quanity: 1,
      },
      {
        product_id:57,
        product_name:"Denim",
        product_price:2199,
        product_description:"Cropped denim blazers",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "57.1.jpg",
        product_img2: "57.2.jpg",
        product_rating:4.5,
        product_quanity: 1,
      },
      {
        product_id:58,
        product_name:"ZARA",
        product_price:1499,
        product_description:"Slim long sized blazer ",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "58.1.jpg",
        product_img2: "58.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:59,
        product_name:"ZARA",
        product_price:1299,
        product_description:"Printed quilted blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "59.1.jpg",
        product_img2: "59.2.jpg",
        product_rating:4.9,
        product_quanity: 1,
      },
      {
        product_id:60,
        product_name:"ZARA",
        product_price:3599,
        product_description:"Fox leather oversized blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "60.1.jpg",
        product_img2: "60.2.jpg",
        product_rating:4.1,
        product_quanity: 1,
      },
      {
        product_id:61,
        product_name:"Denim",
        product_price:1899,
        product_description:"Quilted soft white blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "61.1.jpg",
        product_img2: "61.2.jpg",
        product_rating:4.6,
        product_quanity: 1,
      },
      {
        product_id:62,
        product_name:"Mufti",
        product_price:2199,
        product_description:"Soft cotton oversized blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "62.1.jpg",
        product_img2: "62.2.jpg",
        product_rating:4.3,
        product_quanity: 1,
      },
      {
        product_id:63,
        product_name:"ZARA",
        product_price:3599,
        product_description:"Long structured blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "63.1.jpg",
        product_img2: "63.2.jpg",
        product_rating:4.1,
        product_quanity: 1,
      },
      {
        product_id:64,
        product_name:"ZARA",
        product_price:1999,
        product_description:"Fox oversized blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "64.1.jpg",
        product_img2: "64.2.jpg",
        product_rating:3.9,
        product_quanity: 1,
      },
      {
        product_id:65,
        product_name:"Mufti",
        product_price:2199,
        product_description:"Textured double-breasted blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "65.1.jpg",
        product_img2: "65.2.jpg",
        product_rating:4.3,
        product_quanity: 1,
      },
      {
        product_id:66,
        product_name:"Denim",
        product_price:1899,
        product_description:"Textured houndstooth blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "66.1.jpg",
        product_img2: "66.2.jpg",
        product_rating:4.2,
        product_quanity: 1,
      },
      {
        product_id:67,
        product_name:"ZARA",
        product_price:2199,
        product_description:"Long double-breasted blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "67.1.jpg",
        product_img2: "67.2.jpg",
        product_rating:4.6,
        product_quanity: 1,
      },
      {
        product_id:68,
        product_name:"Mufti",
        product_price:2399,
        product_description:"Houndstooth double-breasted blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "68.1.jpg",
        product_img2: "68.2.jpg",
        product_rating:4.1,
        product_quanity: 1,
      },
      {
        product_id:69,
        product_name:"Denim",
        product_price:2599,
        product_description:"Soft basic blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "69.1.jpg",
        product_img2: "69.2.jpg",
        product_rating:4.3,
        product_quanity: 1,
      },
      {
        product_id:70,
        product_name:"ZARA",
        product_price:1899,
        product_description:"Texture double-breasted blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "70.1.jpg",
        product_img2: "70.2.jpg",
        product_rating:4.8,
        product_quanity: 1,
      },
      {
        product_id:71,
        product_name:"Denim",
        product_price:1899,
        product_description:"Cropped blazer with tight details",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "71.1.jpg",
        product_img2: "71.2.jpg",
        product_rating:4.6,
        product_quanity: 1,
      },
      {
        product_id:72,
        product_name:"ZARA",
        product_price:1899,
        product_description:"Loose fitting blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "72.1.jpg",
        product_img2: "72.2.jpg",
        product_rating:4.4,
        product_quanity: 1,
      },
      {
        product_id:73,
        product_name:"Mufti",
        product_price:1899,
        product_description:"Velvet blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "73.1.jpg",
        product_img2: "73.2.jpg",
        product_rating:4.3,
        product_quanity: 1,
      },
      {
        product_id:74,
        product_name:"Denim",
        product_price:1899,
        product_description:"Textured cardign with button blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "74.1.jpg",
        product_img2: "74.1.jpg",
        product_rating:4.1,
        product_quanity: 1,
      },
      {
        product_id:75,
        product_name:"ZARA",
        product_price:1899,
        product_description:"Shawl lapel blazer",
        product_category:"Ladies",
        product_category_type: "Blazers",
        product_img: "75.1.jpg",
        product_img2: "75.2.jpg",
        product_rating:4.2,
        product_quanity: 1,
      },

    //  ----- TOP Dress Starts Here
    {
      product_id:76,
      product_name:"Denim",
      product_price:1899,
      product_description:"Satin Crop top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "76.1.jpg",
      product_img2: "76.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },

    {
      product_id:77,
      product_name:"ZARA",
      product_price:1899,
      product_description:"TRF rhinestone top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "77.1.jpg",
      product_img2: "77.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:78,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Short textured top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "78.1.jpg",
      product_img2: "78.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:79,
      product_name:"Denim",
      product_price:1899,
      product_description:"Seamless crop top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "79.1.jpg",
      product_img2: "79.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:80,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Draped fit top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "80.1.jpg",
      product_img2: "80.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:81,
      product_name:"Denim",
      product_price:1899,
      product_description:"Cardign top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "81.1.jpg",
      product_img2: "81.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:82,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Oversized top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "82.1.jpg",
      product_img2: "82.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:83,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Ribbed top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "83.1.jpg",
      product_img2: "83.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:84,
      product_name:"Denim",
      product_price:1899,
      product_description:"Crop top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "84.1.jpg",
      product_img2: "84.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:85,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Asymmetric crop top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "85.1.jpg",
      product_img2: "85.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:86,
      product_name:"Denim",
      product_price:1899,
      product_description:"Faux inspired top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "86.1.jpg",
      product_img2: "86.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:87,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Organza bandeau top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "87.1.jpg",
      product_img2: "87.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:88,
      product_name:"Denim",
      product_price:1899,
      product_description:"Butterfly crop top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "88.1.jpg",
      product_img2: "88.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:89,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Sparkly crop fit top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "89.1.jpg",
      product_img2: "89.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:90,
      product_name:"Denim",
      product_price:1899,
      product_description:"Cropped corsetry top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "90.1.jpg",
      product_img2: "90.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:91,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Knit sweater top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "91.1.jpg",
      product_img2: "91.1.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:92,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Asymmetric top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "92.1.jpg",
      product_img2: "92.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:93,
      product_name:"Denim",
      product_price:1899,
      product_description:"Straight oversized blazer",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "93.1.jpg",
      product_img2: "93.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:94,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Shiny blazer dresss",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "94.1.jpg",
      product_img2: "94.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:95,
      product_name:"Denim",
      product_price:1899,
      product_description:"Seamless top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "95.1.jpg",
      product_img2: "95.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:96,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Matching trapped top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "96.1.jpg",
      product_img2: "96.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:97,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Houndstooth double top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "97.1.jpg",
      product_img2: "97.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:98,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Buttoned longline top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "98.1.jpg",
      product_img2: "98.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:99,
      product_name:"Denim",
      product_price:1899,
      product_description:"Shawl lapel top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "99.1.jpg",
      product_img2: "99.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:100,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Lace up top",
      product_category:"Ladies",
      product_category_type: "Top",
      product_img: "100.1.jpg",
      product_img2: "100.1.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },

    //------------------- Jackets Starts Here ------------------------//
    {
      product_id:101,
      product_name:"Denim",
      product_price:1899,
      product_description:"Cropped straight fit denim jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "101.1.jpg",
      product_img2: "101.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:102,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Double faced jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "102.1.jpg",
      product_img2: "102.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:103,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Faux fur hooded jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "103.1.jpg",
      product_img2: "103.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:104,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Faux leather oversized jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "104.1.jpg",
      product_img2: "104.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:105,
      product_name:"Denim",
      product_price:1899,
      product_description:"Denim cropeed jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "105.1.jpg",
      product_img2: "105.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:106,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Contrast puffer jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "106.1.jpg",
      product_img2: "106.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:107,
      product_name:"Denim",
      product_price:1899,
      product_description:"Padded jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "107.1.jpg",
      product_img2: "107.1.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:108,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Water Repellent quilted jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "108.1.jpg",
      product_img2: "108.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:109,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Oversized bomber jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "109.1.jpg",
      product_img2: "109.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:110,
      product_name:"Denim",
      product_price:1899,
      product_description:"Denim fitting jacket ",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "110.1.jpg",
      product_img2: "110.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:111,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Faux leather jacket with chain",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "111.1.jpg",
      product_img2: "111.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:112,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Cotton jacket with bidded",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "112.1.jpg",
      product_img2: "112.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:113,
      product_name:"Denim",
      product_price:1899,
      product_description:"Oversized denim jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "113.1.jpg",
      product_img2: "113.1.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:114,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Soft jacket ",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "114.1.jpg",
      product_img2: "114.1.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:115,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Cropped denim jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "115.1.jpg",
      product_img2: "115.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:116,
      product_name:"Denim",
      product_price:1899,
      product_description:"Printed quilted jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "116.1.jpg",
      product_img2: "116.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:117,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Faux suede jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "117.1.jpg",
      product_img2: "117.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:118,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Rubbersized Puffer jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "118.1.jpg",
      product_img2: "118.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:119,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Long quilted jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "119.1.jpg",
      product_img2: "119.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:120,
      product_name:"Denim",
      product_price:1899,
      product_description:"Packway puffer coat jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "120.1.jpg",
      product_img2: "120.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:121,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Textured cardign jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "121.1.jpg",
      product_img2: "121.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:122,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Trench fitted jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "122.1.jpg",
      product_img2: "122.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:123,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Textured Double-breasted jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "123.1.jpg",
      product_img2: "123.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:124,
      product_name:"Denim",
      product_price:1899,
      product_description:"Wool blend fitted jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "124.1.jpg",
      product_img2: "124.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:125,
      product_name:"Mufti",
      product_price:1899,
      product_description:"Oversized satin jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "125.1.jpg",
      product_img2: "125.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },
    {
      product_id:126,
      product_name:"ZARA",
      product_price:1899,
      product_description:"Knit wi neck jacket",
      product_category:"Ladies",
      product_category_type: "Jackets",
      product_img: "126.1.jpg",
      product_img2: "126.2.jpg",
      product_rating:4.2,
      product_quanity: 1,
    },



    ]
  }
}
